// Generated by https://quicktype.io


export interface Servicios {
    _id:            string;
    nombreCliente:  string;
    primerApellido: string;
    segundoApelldio: string;
    email:          string;
    telefono:       string;
    marcaEquipo:    string;
    modeloEquipo:   string;
    falla:          string;
    accesorio:      string;
    adelanto:       number;
    costoTotal:     number;
    productos:      string;
    estado:         string;
}
